CREATE DATABASE TECHSTORE_SA;
USE TECHSTORE_SA;


-- Categorías de Productos
CREATE TABLE CATEGORIAS_PRODUCTOS (
    NOMBRE_CATEGORIA VARCHAR(50) PRIMARY KEY
);

-- Clientes
CREATE TABLE CLIENTES (
    ID_CLIENTE INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    CORREO_ELECTRONICO VARCHAR(100)
);

-- Marcas
CREATE TABLE MARCAS (
    NOMBRE_MARCA VARCHAR(50) PRIMARY KEY
);

-- Productos
CREATE TABLE PRODUCTOS (
    NOMBRE_PRODUCTO VARCHAR(50) PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR(50),
    NOMBRE_MARCA VARCHAR(50),
    PRECIO DECIMAL(18, 0),
    CONSTRAINT FK_PRODUCTOS_CATEGORIA FOREIGN KEY (NOMBRE_CATEGORIA) REFERENCES CATEGORIAS_PRODUCTOS(NOMBRE_CATEGORIA),
    CONSTRAINT FK_PRODUCTOS_MARCA FOREIGN KEY (NOMBRE_MARCA) REFERENCES MARCAS(NOMBRE_MARCA)
);


-- Vendedores
CREATE TABLE VENDEDORES (
    NOMBRE_VENDEDOR VARCHAR(50) PRIMARY KEY
);

-- Ventas
CREATE TABLE VENTAS (
    ID_VENTA INT PRIMARY KEY,
    NOMBRE_VENDEDOR VARCHAR(50),
    NOMBRE_PRODUCTO VARCHAR(50),
    FECHA_VENTA DATE,
    CANTIDAD INT,
    ID_CLIENTE INT,
    CONSTRAINT FK_VENTA_VENDEDORES FOREIGN KEY (NOMBRE_VENDEDOR) REFERENCES VENDEDORES(NOMBRE_VENDEDOR),
    CONSTRAINT FK_VENTA_PRODUCTOS FOREIGN KEY (NOMBRE_PRODUCTO) REFERENCES PRODUCTOS(NOMBRE_PRODUCTO),
    CONSTRAINT FK_VENTA_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);
-- Inserciones en CATEGORIAS_PRODUCTOS
INSERT INTO CATEGORIAS_PRODUCTOS (NOMBRE_CATEGORIA) VALUES
('Smartphones'),
('Laptops'),
('Accesorios'),
('Electrodomésticos');

-- Inserciones en CLIENTES
INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, CORREO_ELECTRONICO) VALUES
(1, 'Juan', 'Pérez', 'juan@example.com'),
(2, 'María', 'Gómez', 'maria@example.com'),
(3, 'Pedro', 'Sánchez', 'pedro@example.com'),
(4, 'Ana', 'Martínez', 'ana@example.com');

-- Inserciones en MARCAS
INSERT INTO MARCAS (NOMBRE_MARCA) VALUES
('Samsung'),
('Apple'),
('HP'),
('LG');

-- Inserciones en PRODUCTOS
INSERT INTO PRODUCTOS (NOMBRE_PRODUCTO, NOMBRE_CATEGORIA, NOMBRE_MARCA, PRECIO) VALUES
('iPhone 13', 'Smartphones', 'Apple', 1000),
('Galaxy S21', 'Smartphones', 'Samsung', 900),
('HP Pavilion', 'Laptops', 'HP', 1200),
('LG Refrigerator', 'Electrodomésticos', 'LG', 1500);